import { PsychQuestion } from '../types/psych'

export const PSYCH_QUESTIONS: PsychQuestion[] = [
  // Animals
  { question: "What is a group of flamingos called?", realAnswer: "A flamboyance" },
  { question: "What is a group of porcupines called?", realAnswer: "A prickle" },
  { question: "What animal is born with fingerprints almost identical to humans?", realAnswer: "Koala" },
  { question: "What is the only mammal that can truly fly?", realAnswer: "Bat" },
  { question: "What color is a hippo's sweat?", realAnswer: "Red" },
  { question: "How many hearts does an octopus have?", realAnswer: "Three" },
  { question: "What is a group of owls called?", realAnswer: "A parliament" },
  { question: "What is the fastest land animal?", realAnswer: "Cheetah" },
  { question: "What animal can sleep for three years straight?", realAnswer: "Snail" },
  { question: "What is a baby puffin called?", realAnswer: "A puffling" },
  { question: "What is the only bird that can fly backwards?", realAnswer: "Hummingbird" },
  { question: "What is a group of crows called?", realAnswer: "A murder" },
  { question: "What animal has the longest pregnancy?", realAnswer: "Elephant (22 months)" },
  { question: "What is a group of jellyfish called?", realAnswer: "A smack" },
  { question: "What is the loudest animal on Earth?", realAnswer: "Sperm whale" },

  // History
  { question: "What was the shortest war in history?", realAnswer: "Anglo-Zanzibar War (38 minutes)" },
  { question: "What did ancient Romans use as mouthwash?", realAnswer: "Urine" },
  { question: "What was the first toy advertised on television?", realAnswer: "Mr. Potato Head" },
  { question: "In what year was the first email sent?", realAnswer: "1971" },
  { question: "What was Cleopatra's native language?", realAnswer: "Greek" },
  { question: "Which U.S. president was also a licensed bartender?", realAnswer: "Abraham Lincoln" },
  { question: "What was the original name of New York City?", realAnswer: "New Amsterdam" },
  { question: "How old was the youngest pope in history?", realAnswer: "18 years old" },
  { question: "What ancient civilization invented the first vending machine?", realAnswer: "Ancient Greece" },
  { question: "What was the first country to give women the right to vote?", realAnswer: "New Zealand" },
  { question: "What year were the first modern Olympic Games held?", realAnswer: "1896" },
  { question: "What color were carrots before the 17th century?", realAnswer: "Purple" },

  // Science
  { question: "What percentage of the Earth's water is fresh water?", realAnswer: "About 3%" },
  { question: "How long does it take for light from the Sun to reach Earth?", realAnswer: "About 8 minutes" },
  { question: "What is the hardest natural substance on Earth?", realAnswer: "Diamond" },
  { question: "What gas makes up most of Earth's atmosphere?", realAnswer: "Nitrogen (78%)" },
  { question: "How many bones does a shark have?", realAnswer: "Zero (they have cartilage)" },
  { question: "What is the chemical symbol for gold?", realAnswer: "Au" },
  { question: "At what temperature are Celsius and Fahrenheit equal?", realAnswer: "-40 degrees" },
  { question: "What planet rains diamonds?", realAnswer: "Neptune" },
  { question: "How many taste buds does the average human tongue have?", realAnswer: "About 10,000" },
  { question: "What is the most abundant element in the universe?", realAnswer: "Hydrogen" },
  { question: "What is the speed of sound in miles per hour?", realAnswer: "About 767 mph" },
  { question: "How many muscles does a caterpillar have?", realAnswer: "About 4,000" },

  // Language & Words
  { question: "What is the longest word in English with no repeated letters?", realAnswer: "Uncopyrightable" },
  { question: "What is the dot over the letter 'i' called?", realAnswer: "A tittle" },
  { question: "What is the fear of long words called?", realAnswer: "Hippopotomonstrosesquippedaliophobia" },
  { question: "What is the most common letter in the English language?", realAnswer: "E" },
  { question: "What word is spelled incorrectly in every dictionary?", realAnswer: "Incorrectly" },
  { question: "What is the shortest complete sentence in English?", realAnswer: "I am" },
  { question: "What does the word 'karate' literally mean in Japanese?", realAnswer: "Empty hand" },
  { question: "What is a group of pandas called?", realAnswer: "An embarrassment" },
  { question: "What does 'wiki' mean in Hawaiian?", realAnswer: "Quick" },
  { question: "What is the oldest word in the English language still in use?", realAnswer: "I" },

  // Pop Culture & Entertainment
  { question: "What was the first feature-length animated movie?", realAnswer: "Snow White and the Seven Dwarfs" },
  { question: "What is the best-selling video game of all time?", realAnswer: "Minecraft" },
  { question: "What was Mickey Mouse's original name?", realAnswer: "Mortimer Mouse" },
  { question: "What is the most-watched YouTube video of all time?", realAnswer: "Baby Shark Dance" },
  { question: "What was the first movie to make over $1 billion at the box office?", realAnswer: "Titanic" },
  { question: "What color were Coca-Cola cans before they were red?", realAnswer: "They were always red" },
  { question: "What was Google's original name?", realAnswer: "Backrub" },
  { question: "How many Monopoly properties are there?", realAnswer: "28" },
  { question: "What is the name of the coffee shop in Friends?", realAnswer: "Central Perk" },
  { question: "What was YouTube's first ever uploaded video called?", realAnswer: "Me at the zoo" },

  // Food & Drink
  { question: "What fruit is the most popular worldwide?", realAnswer: "Banana" },
  { question: "What is the most stolen food in the world?", realAnswer: "Cheese" },
  { question: "What food never spoils?", realAnswer: "Honey" },
  { question: "How many grapes does it take to make one bottle of wine?", realAnswer: "About 600-800" },
  { question: "What is the most expensive spice in the world by weight?", realAnswer: "Saffron" },
  { question: "What nut is used to make marzipan?", realAnswer: "Almond" },
  { question: "What fruit has its seeds on the outside?", realAnswer: "Strawberry" },
  { question: "What country consumes the most chocolate per capita?", realAnswer: "Switzerland" },
  { question: "What is the hottest chili pepper in the world?", realAnswer: "Carolina Reaper" },
  { question: "How many calories are in a single almond?", realAnswer: "About 7" },

  // Geography
  { question: "What is the smallest country in the world?", realAnswer: "Vatican City" },
  { question: "What country has the most islands?", realAnswer: "Sweden (about 267,570)" },
  { question: "What is the longest river in the world?", realAnswer: "The Nile" },
  { question: "What is the driest place on Earth?", realAnswer: "McMurdo Dry Valleys, Antarctica" },
  { question: "What country has the most time zones?", realAnswer: "France (12)" },
  { question: "What is the tallest mountain in the solar system?", realAnswer: "Olympus Mons on Mars" },
  { question: "What percentage of the Earth's surface is covered by water?", realAnswer: "About 71%" },
  { question: "What is the deepest point in the ocean?", realAnswer: "Mariana Trench" },
  { question: "What country is home to the most active volcanoes?", realAnswer: "Indonesia" },
  { question: "What is the largest desert in the world?", realAnswer: "Antarctic Desert" },

  // Human Body
  { question: "How many times does the average heart beat per day?", realAnswer: "About 100,000" },
  { question: "What is the strongest muscle in the human body?", realAnswer: "Masseter (jaw muscle)" },
  { question: "How long is the average person's small intestine?", realAnswer: "About 20 feet" },
  { question: "What percentage of your body is water?", realAnswer: "About 60%" },
  { question: "How many bones are in the human hand?", realAnswer: "27" },
  { question: "What organ uses 20% of your body's energy?", realAnswer: "The brain" },
  { question: "How fast do fingernails grow per month?", realAnswer: "About 3-4 millimeters" },
  { question: "How many muscles does it take to smile?", realAnswer: "About 12" },

  // Technology
  { question: "What was the first commercially available cell phone?", realAnswer: "Motorola DynaTAC 8000X" },
  { question: "How much did the first computer mouse weigh?", realAnswer: "About 1 pound" },
  { question: "What does 'HTTP' stand for?", realAnswer: "HyperText Transfer Protocol" },
  { question: "In what year was the first iPhone released?", realAnswer: "2007" },
  { question: "What was the first website ever created about?", realAnswer: "The World Wide Web project itself" },
  { question: "How many lines of code does the average car have?", realAnswer: "About 100 million" },

  // Sports
  { question: "What sport was the first to be played on the moon?", realAnswer: "Golf" },
  { question: "How long is an Olympic swimming pool in meters?", realAnswer: "50 meters" },
  { question: "What is the diameter of a basketball hoop in inches?", realAnswer: "18 inches" },
  { question: "How many dimples are on an average golf ball?", realAnswer: "About 336" },
  { question: "What country invented the game of chess?", realAnswer: "India" },

  // Random Fun Facts
  { question: "What is the official national animal of Scotland?", realAnswer: "Unicorn" },
  { question: "How many years can a lobster live?", realAnswer: "Over 100 years" },
  { question: "What is the name of the fear of cooking?", realAnswer: "Mageirocophobia" },
  { question: "What percentage of people have never made or received a phone call?", realAnswer: "About 50%" },
  { question: "What is the average number of dreams a person has per night?", realAnswer: "3-5 dreams" },
  { question: "How many possible combinations are there on a Rubik's Cube?", realAnswer: "Over 43 quintillion" },
  { question: "What is the world record for the longest hiccuping spree?", realAnswer: "68 years" },
  { question: "How many keys does a standard piano have?", realAnswer: "88" },
  { question: "What is the most common birthday in the United States?", realAnswer: "September 9th" },
  { question: "What is the average lifespan of a taste bud?", realAnswer: "About 10 days" },
  { question: "How many people are airborne over the US at any given time?", realAnswer: "About 500,000" },
  { question: "What color do most people see when they close their eyes?", realAnswer: "Dark reddish-brown (eigengrau)" },
]
