// Each pair: [civilianWord, undercoverWord]
// Words should be similar enough to create ambiguity but different enough to distinguish
export const WORD_PAIRS: [string, string][] = [
  ['Pizza', 'Pasta'],
  ['Ocean', 'Lake'],
  ['Mountain', 'Hill'],
  ['Doctor', 'Nurse'],
  ['Mustache', 'Beard'],
  ['Bicycle', 'Motorcycle'],
  ['Painting', 'Drawing'],
  ['Telescope', 'Binoculars'],
  ['Newspaper', 'Magazine'],
  ['Coffee', 'Tea'],
  ['Wallet', 'Purse'],
  ['Candle', 'Lamp'],
  ['Elevator', 'Escalator'],
  ['Pillow', 'Cushion'],
  ['Stadium', 'Arena'],
  ['Helicopter', 'Airplane'],
  ['Sweater', 'Jacket'],
  ['Sandwich', 'Burger'],
  ['Library', 'Bookstore'],
  ['Diamond', 'Crystal'],
  ['Compass', 'Map'],
  ['Tattoo', 'Sticker'],
  ['Igloo', 'Tent'],
  ['Suitcase', 'Backpack'],
  ['Pancake', 'Waffle'],
  ['Lighthouse', 'Tower'],
  ['Dolphin', 'Whale'],
  ['Sword', 'Knife'],
  ['Laptop', 'Tablet'],
  ['Curtain', 'Blinds'],
  ['Hammock', 'Swing'],
  ['Cactus', 'Palm Tree'],
  ['Typewriter', 'Keyboard'],
  ['Submarine', 'Ship'],
  ['Microphone', 'Speaker'],
  ['Crayon', 'Marker'],
  ['Aquarium', 'Zoo'],
  ['Limousine', 'Taxi'],
  ['Bow Tie', 'Necktie'],
  ['Magnet', 'Glue'],
  ['Balcony', 'Terrace'],
  ['Owl', 'Eagle'],
  ['Flamingo', 'Swan'],
  ['Puzzle', 'Crossword'],
  ['Brownie', 'Cookie'],
  ['Greenhouse', 'Garden'],
  ['Skateboard', 'Scooter'],
  ['Popcorn', 'Nachos'],
  ['Bungalow', 'Apartment'],
  ['Siren', 'Alarm'],
  ['Whistle', 'Horn'],
  ['Fireplace', 'Bonfire'],
  ['Pudding', 'Custard'],
  ['Werewolf', 'Vampire'],
  ['Astronaut', 'Pilot'],

  // Hindi / Hinglish pairs
  ['Chai', 'Doodh'],
  ['Samosa', 'Kachori'],
  ['Paratha', 'Roti'],
  ['Jalebi', 'Gulab Jamun'],
  ['Biryani', 'Pulao'],
  ['Paan', 'Supari'],
  ['Chaat', 'Golgappa'],
  ['Lassi', 'Chaach'],
  ['Kulfi', 'Ice Cream'],
  ['Achaar', 'Chutney'],
  ['Diwali', 'Holi'],
  ['Garba', 'Bhangra'],
  ['Mehndi', 'Choodi'],
  ['Bindi', 'Sindoor'],
  ['Aarti', 'Pooja'],
  ['Baraat', 'Vidaai'],
  ['Kurta', 'Sherwani'],
  ['Saree', 'Lehenga'],
  ['Chappal', 'Jooti'],
  ['Lungi', 'Dhoti'],
  ['Scooty', 'Bullet'],
  ['Bhabhi', 'Didi'],
]
